### ISSUE TITLE
IPTC Photo Metadata Standard 2021.1 values

### ISSUE THREAD

**Issue by postscript-dev** [exiftool/exiftool#116]
While adding the new [IPTC Photo Metadata Standard 2021.1](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata-2021.1.html) to Exiv2, I looked at the way in which ExifTool supports the standard. There are several additional translation tables that could be added to ExifTool, as some tags use a closed choice set of values.

e.g. The IPTC tag [6.21. Scene Code](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata-2021.1.html#scene-code) corresponds to the [Scene](https://www.exiftool.org/TagNames/XMP.html#iptcCore) tag in ExifTool.

**Comment by boardhead** [comment]
Of the 7 closed-choice tags in that specification (BoundaryShape, BoundaryMeasuringUnit, CountryCode, CountryISOCode, ImageRating, SceneCode, SubjectCode), ExifTool implements a lookup for only 2 of them (BoundaryShape and BoundaryMeasuringUnit).  The CountryCode's aren't implemented because the list is long and not forward compatible for new country names, and the codes are meaningful on their own.  ImageRating is meaningful as a number, and I don't think it is really a closed choice anyway since it is "real" format and not "integer".  SceneCode and SubjectCode aren't implemented because there hasn't been a request yet, and there are more than 1400 SubjectCode values currently defined, and I worry about forward compatibility for both of these (if I restrict writing of these to a closed list, then users won't be able to easily add new values as they are defined).

So unless this is a formal request to add additional lookups, I think it would be best to leave things as they are.

**Comment by postscript-dev** [comment]
Thanks for taking the time to explain, I now have more of an idea what is useful for the project.

> if I restrict writing of these to a closed list, then users won't be able to easily add new values as they are defined

This is one of the differences between ExifTool and Exiv2. In Exiv2, the tables are only used as an optional output and not to validate user values.

I am happy to close this.

**Comment by boardhead** [comment]
The tables in ExifTool are optional as well, but the user has to know about the -n option to do this.
