### ISSUE TITLE
Turkish Encoding Inconsistency

### ISSUE THREAD

**Issue by bagsergen** [exiftool/exiftool#127]
Hi, thanks for exiftool.
I'm trying to write Turkish characters ( exp: ĞÜŞİÖÇğüşiöç ) to image files but I couldn't. I set charset combination but, it didn't what I want. Is there anyone can help me ?

Thanks.

My codes:
Write:

- `exiftool -charset exiftool=cp1254 -NewXMPxxxTag3="ĞÜŞİÖÇğüşiöç" -overwrite_original abc.jpg`
- `exiftool -charset exiftool=cp1254 -Keywords="ĞÜŞİÖÇğüşiöç" -overwrite_original abc.jpg`

Show:

- `exiftool -charset exiftool=cp1254 -NewXMPxxxTag3 abc.jpg`
- `exiftool -charset exiftool=cp1254 -Keywords abc.jpg`

Expectation:

- New XM Pxxx Tag 3               : ĞÜŞİÖÇğüşiöç
- Keywords                               : ĞÜŞİÖÇğüşiöç

Actual:

- New XM Pxxx Tag 3               : GÜSIÖÇgüsiöç
- Keywords                               : GÜSIÖÇgüsiöç

![Capture](https://user-images.githubusercontent.com/53207601/158581230-435aa370-785f-4fe6-afc3-0a9fb9cfda4c.PNG)

Sample abc.jpg

![abc](https://user-images.githubusercontent.com/53207601/158581217-5bea7ceb-e935-45e3-a78c-13827f36d9a9.jpg)

**Comment by StarGeekSpaceNerd** [comment]
You don't mention your OS but I'm guessing that it's Windows.  The problem is that Windows command line doesn't work very well with any characters other than basic ASCII.

First try the option listed in [FAQ #18](https://exiftool.org/faq.html#Q18).  Changing the codepage for the shell may work for you.  You might also try adding the [`-L` (latin) option](https://exiftool.org/exiftool_pod.html#L--latin). You should also check [FAQ #10](https://exiftool.org/faq.html#Q10).

Unfortunately, that never did work for me. Instead, I had to go with [this StackOverflow answer](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096).  This may have the side effect of changing fonts and GUIs in some older programs.  See [this exiftool forum post](https://exiftool.org/forum/index.php?topic=13370.msg72233#msg72233) for an example.  You'll have to decide if this is an acceptable trade off based upon the program you use.

The final options I can offer would be using the text file option as mentioned in FAQ 18.  Another option, which I used for the longest time, is to convert the characters into html entities and use the [`-E` (`-escapeHTML`) option](https://exiftool.org/exiftool_pod.html#E--ex--ec--escapeHTML--escapeXML--escapeC).  There are [online converters](https://mothereff.in/html-entities#%C4%9E%C3%9C%C5%9E%C4%B0%C3%96%C3%87%C4%9F%C3%BC%C5%9Fi%C3%B6%C3%A7) that will do the conversion. Myself, I used a Autoit3 script which I posted [here](https://exiftool.org/forum/index.php?topic=12986.msg70191#msg70191).  The resulting command would be 
`exiftool -IPTC:CodedCharacterSet=utf8 -E -Keywords="&#x11E;&#xDC;&#x15E;&#x130;&#xD6;&#xC7;&#x11F;&#xFC;&#x15F;i&#xF6;&#xE7;" -overwrite_original abc.jpg
`
Here I also set the `IPTC:CodedCharacterSet` which I would recommend to add when using IPTC IIM/Legacy tags.  It isn't necessary for XMP, such as IPTC Core/Ext, as those are supposed to be in UTF8.

**Comment by bagsergen** [comment]
Hi @StarGeekSpaceNerd, thanks for your supporting. You are right about my OS (Windows). I tried all option you told, just only last option fixed my problem. I used this code `exiftool -IPTC:CodedCharacterSet=utf8 -E -Keywords="&#x11E;&#xDC;&#x15E;&#x130;&#xD6;&#xC7;&#x11F;&#xFC;&#x15F;i&#xF6;&#xE7;" -overwrite_original abc.jpg` and it fixed.

Many thanks ⭐
