### ISSUE TITLE
Is exiftool able to handle mp4 QuickTime metadata?

### ISSUE THREAD

**Issue by MagnusOxlund** [exiftool/exiftool#136]
I would ask this question on the forum, but unfortunately I'm not receiving the account activation emails.

I'm trying to wipe all metadata from a number of .mp4 files with tags in the QuickTime namespace using the command `exiftool -all= path/to/file.mp4`, but the command isn't erasing any of the QuickTime tags.

I've searched the forum and found a few old responses indicating exiftool doesn't handle .mp4 metadata. Is that the current official stance on .mp4 files, or has that feature been added since? 

MP4 is on the list of supported file types in `exiftool --help`, but QuickTime isn't listed on the non-exhaustive list of supported meta information categories.

The [online documentation section on the QuickTime format](https://exiftool.org/TagNames/QuickTime.html) states the following:

> ExifTool currently writes only top-level metadata in QuickTime-based files; it extracts other track-specific and timed metadata, but can not yet edit tags in these locations (with the exception of track-level date/time tags).

Assuming this means exiftool only has access to edit a subset of QuickTime tags, I'm still wondering why certain tags listed as "int32u" in the "writable" column on that same documentation page, e.g., "CreateDate", are not erased from my particular .mp4 files using the above command?

I'm running exiftool version 12.4 on MacOS.

**Comment by StarGeekSpaceNerd** [comment]
Exiftool can edit any tag that is listed as `writable` on the Quicktime tags page, but some tags, such as the integer based timestamps, e.g. `CreateDate`, `ModifyDate`, and the track create/modify dates, cannot be removed, only set to 0, which is what exiftool will do when you use a command such as `-CreateDate=`  They are an intrinsic part of the specs.

There are also other things that exiftool can't edit/remove from video files because there isn't a standard for them.  Things like EXIF data and GPS tracks are shoehorned into the file in varying ways which differ between each camera manufacturer, some times differing between models from the same manufacturer.

My suggestion to make sure everything is removed from the file that can be removed is to use ffmpeg.  A command such as this will remux the file without recompressing, which will remove all data.
`ffmpeg -i input.mp4 -c copy -map 0 output.mp4`

**Comment by StarGeekSpaceNerd** [comment]
As for the problem with the account activation email, hopefully when Phil sees this he can check on it.  There have been [problems with the server load](https://exiftool.org/forum/index.php?topic=13495.0) and he's been trying to adjust things.  This might have been something hit by the adjustments.

**Comment by MagnusOxlund** [comment]
Thank you @StarGeekSpaceNerd for the context on the forum signup process.

On the .mp4/QuickTime issue, here's a sample of the debugging output generated when running the above command on one of the files (`exiftool -all= -V2 sample.mp4`):

```
(EXIF) user@user project % exiftool -all= -V2 sample.mp4 
  Deleting tags in: * AFCP APP0 APP1 APP10 APP11 APP12 APP13 APP14 APP15 APP2 APP3 APP4 APP5 APP6 APP7 APP8 APP9 CIFF CanonVRD Ducky EXIF ExifIFD File FlashPix FotoStation GPS ICC_Profile IFD0 IPTC Insta360 ItemList ItemList JFIF Jpeg2000 Keys Keys MIE MPF MakerNotes Meta MetaIFD Microsoft NikonApp NikonCapture PDF PNG PNG-pHYs PhotoMechanic Photoshop PrintIM QuickTime RMETA RSRC Trailer UserData UserData XML XML-* XML-* XMP XMP-* XMP-*
======== sample.mp4
Rewriting sample.mp4...
  FileType = MP4
  FileTypeExtension = MP4
  MIMEType = video/mp4
  Editing tags in: * AFCP APP0 APP1 APP10 APP11 APP12 APP13 APP14 APP15 APP2 APP3 APP4 APP5 APP6 APP7 APP8 APP9 CIFF CanonVRD Comment Ducky ExifIFD FlashPix FotoStation GPS ICC_Profile IFD0 IPTC Insta360 ItemList JFIF Jpeg2000 Keys MIE MOV MPF MakerNotes Meta MetaIFD Microsoft Movie NikonApp NikonCapture PDF PNG PNG-pHYs PhotoMechanic Photoshop PrintIM QuickTime RMETA RSRC Trailer UserData XML XML-* XMP 
  Creating tags in: 
  Rewriting Movie
  Rewriting MovieHeader
  Rewriting Track
  Rewriting TrackHeader
  Rewriting Media
  Rewriting MediaHeader
  Rewriting MediaInfo
  Rewriting DataInfo
  Rewriting DataRef
  Rewriting SampleTable
  Rewriting Track
  Rewriting TrackHeader
  Rewriting Media
  Rewriting MediaHeader
  Rewriting MediaInfo
  Rewriting DataInfo
  Rewriting DataRef
  Rewriting SampleTable
  Deleting XMP
    (XMP changed size)
    1 image files updated>
```

**Comment by StarGeekSpaceNerd** [comment]
That all appears to be things that can't be removed.  Properties of the file that are required to render the video.

Do you have something specific that you want removed but can't?  Use the command in [FAQ #3](https://exiftool.org/faq.html#Q3) to list the tag name and group it belongs to.

**Comment by boardhead** [comment]
Using -all= (or any other group delete) has no effect on permanent tags.  You can "delete" QuickTime:CreateDate individually, and it will get set to zero.  Also, you can delete all date/time tags individually like with -time:all=, which I admit may be counterintuitive, but specifying a family 2 group name is effectively like a wildcard delete of individual tags, and isn't a group delete.

The forum activation shouldn't be affected by the server load.  I see only one account (userid "azin") from today that still requires activation.  If that is you, I can activate it manually.  Most forum email problems are due to spam filters on the user side.

- Phil

**Comment by StarGeekSpaceNerd** [comment]
> Using -all= (or any other group delete) has no effect on permanent tags

Ahh, I missed that somehow.

Putting all the examples together.

```
C:\>exiftool -time:all --system:all -G1 -a -s Y:\!temp\aa\Test.mp4
[QuickTime]     CreateDate                      : 2022:04:28 11:30:39
[QuickTime]     ModifyDate                      : 2022:04:28 11:30:39
[Track1]        TrackCreateDate                 : 2022:04:28 11:30:39
[Track1]        TrackModifyDate                 : 2022:04:28 11:30:39
[Track1]        MediaCreateDate                 : 2022:04:28 11:30:39
[Track1]        MediaModifyDate                 : 2022:04:28 11:30:39
[Track2]        TrackCreateDate                 : 2022:04:28 11:30:39
[Track2]        TrackModifyDate                 : 2022:04:28 11:30:39
[Track2]        MediaCreateDate                 : 2022:04:28 11:30:39
[Track2]        MediaModifyDate                 : 2022:04:28 11:30:39
[UserData]      DateTimeOriginal                : 2022:04:28 04:30:39-07:00

C:\>exiftool -P -overwrite_original -All:All= Y:\!temp\aa\Test.mp4
    1 image files updated

C:\>exiftool -time:all --system:all -G1 -a -s Y:\!temp\aa\Test.mp4
[QuickTime]     CreateDate                      : 2022:04:28 11:30:39
[QuickTime]     ModifyDate                      : 2022:04:28 11:30:39
[Track1]        TrackCreateDate                 : 2022:04:28 11:30:39
[Track1]        TrackModifyDate                 : 2022:04:28 11:30:39
[Track1]        MediaCreateDate                 : 2022:04:28 11:30:39
[Track1]        MediaModifyDate                 : 2022:04:28 11:30:39
[Track2]        TrackCreateDate                 : 2022:04:28 11:30:39
[Track2]        TrackModifyDate                 : 2022:04:28 11:30:39
[Track2]        MediaCreateDate                 : 2022:04:28 11:30:39
[Track2]        MediaModifyDate                 : 2022:04:28 11:30:39

C:\>exiftool -P -overwrite_original -Time:All= Y:\!temp\aa\Test.mp4
    1 image files updated

C:\>exiftool -time:all --system:all -G1 -a -s Y:\!temp\aa\Test.mp4
[QuickTime]     CreateDate                      : 0000:00:00 00:00:00
[QuickTime]     ModifyDate                      : 0000:00:00 00:00:00
[Track1]        TrackCreateDate                 : 0000:00:00 00:00:00
[Track1]        TrackModifyDate                 : 0000:00:00 00:00:00
[Track1]        MediaCreateDate                 : 0000:00:00 00:00:00
[Track1]        MediaModifyDate                 : 0000:00:00 00:00:00
[Track2]        TrackCreateDate                 : 0000:00:00 00:00:00
[Track2]        TrackModifyDate                 : 0000:00:00 00:00:00
[Track2]        MediaCreateDate                 : 0000:00:00 00:00:00
[Track2]        MediaModifyDate                 : 0000:00:00 00:00:00
```

**Comment by MagnusOxlund** [comment]
Thank you very much for the explanation, @boardhead, that answers the question.

As for activation emails, I believe my request may have expired by now, but you might want to look into whether the outlook.com client is letting them through.

**Comment by boardhead** [comment]
If outlook.com is at all popular then it must be OK because out of almost 10000 forum members I have only had a few complain they haven't received an email, although there are 95 outstanding activation requests from the last 3 years so maybe only a small fraction complain about this.  The forum activation requests never expire, but I manually delete them after a few years.
