### ISSUE TITLE
Exiftool does nothing

### ISSUE THREAD

**Issue by busy128** [exiftool/exiftool#14]
Hello,
I have downloaded "exiftool-11.37.zip" from this page and extracted file "exiftool(-k).exe"
but when I execute the exiftool(-k).exe, it does nothing. After execution, it returns immediatelly
(edit: the console closes immediatelly too).
Older versions have the same behaviour (tested on version from 6.9.2012)
Behaviour seems to be independed of command line parameters (it seems something goes to wrong before cmdline processing).
Errorlevel is not set.
Windows version: Win 7 Enterprise SP1 64bit.

**Comment by boardhead** [comment]
I suspect that you have some antivirus software that is interfering with ExifTool.

**Comment by busy128** [comment]
I'm sure antivirus is no problem. I use Eset and all files (exiftool(-k).exe  with included executable and perl58.dll) are OK and they are not blocked by Eset.

**Comment by boardhead** [comment]
OK then, exactly how are you executing "exiftool(-k).exe"?  By double clicking on its icon?

Try launching from a cmd.exe window to see if it shows any errors.

**Comment by busy128** [comment]
After double clicking, the console appears and then disappears immediatelly.
I have perceived two files dropped into %temp% directory:
exiftool(-k).exe
perl524.dll
I copied both files into my test directory (executable renamed to "exiftool-extracted.exe") and tried them execute from a cmd. After execution of "exiftool(-k).exe", nothing happened and next cmd prompt appears immediatelly. And the both files dropped into %temp% again.
But dropped executable file displayed an error message:
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\Exiftool-test>dir
 Volume in drive D is Work
 Volume Serial Number is 3E8B-4053

 Directory of d:\Exiftool-test

24.04.2019  15:30    <DIR>          .
24.04.2019  15:30    <DIR>          ..
17.04.2019  10:39         8 445 422 exiftool(-k).exe
24.04.2019  15:29            57 856 exiftool-extracted.exe
24.04.2019  15:29         1 932 800 perl524.dll
               3 File(s)     10 436 078 bytes
               2 Dir(s)  334 520 193 024 bytes free

d:\Exiftool-test>exiftool(-k).exe
'exiftool' is not recognized as an internal or external command,
operable program or batch file.

d:\Exiftool-test>"exiftool(-k).exe"

d:\Exiftool-test>exiftool-extracted.exe
Can't locate Win32.pm in @INC (you may need to install the Win32 module) (@INC contains: .) at -e line 488.
BEGIN failed--compilation aborted at -e line 639.

d:\Exiftool-test>
```

**Comment by boardhead** [comment]
Typing [tt]"exiftool(-k).exe"[/tt] at the command prompt should have worked (you need the quotes).

I think the problem may have to do with your TEMP settings.  On Windows 7, the exiftool package normally creates its temporary files in C:\Users\USER\AppData\Local\Temp.  I don't know why you say it is creating them in %temp%, but there should be many more files than just the extracted "exiftool(-k).exe" and perl524.dll.  Also, you shouldn't run the extracted exe directly because the environment won't be set properly.

**Comment by busy128** [comment]
I use %temp% as general substitution of my temporary directory in system. In my windows, I use this setting:
SET TEMP=C:\Temp
SET TMP=C:\Temp
I have both for sure. Free space on C: is more than 6GB, there is no many files (up to 32) and thus temp directory is fully readable and writeable for each user so I think there is no problem with Temp directory.

After executing "exiftool(-k).exe", this directory is created:
C:\Temp\par-736e61767f6d69732e6c6162786b79\cache-exiftool-11.37\
and then two files (mentioned above) is dropped into this directory.
After this, execution of "exiftool(-k).exe" ends without any next visible action.

**Comment by boardhead** [comment]
... and you say that the same thing happened for different versions?  Then it must be something system specific.

The cache-exiftool directory should contain more than 100 files!  Somehow these files are not getting written properly.  I have never seen this problem other than similar things due to antivirus software.  It seems to be some type of bad interaction between your specific system an the PAR packer, and isn't an ExifTool problem as such.  For details about PAR, see https://metacpan.org/pod/PAR -- in particular, see the NOTES section an maybe try changing the environment to use a different temporary directory.  Also take a look at the permissions of your temporary directory, and again, disable any antivirus you may have.
