### ISSUE TITLE
WhiteBalanceFineTune location change in newer Nikon MakerNotes

### ISSUE THREAD

**Issue by kmilos** [exiftool/exiftool#148]
It would seem this tag has moved from 0x0b to 0x3f in Nikon Z 9 MakerNote v2.11

See e.g. https://github.com/darktable-org/darktable/issues/12282

**Comment by kmilos** [comment]
Actually, looks like it's not a move, but a new version of the tag (signed rationals), and can co-exist w/ the original 0x0b tag.

**Comment by boardhead** [comment]
Great, thanks!  This will appear in ExifTool 12.45

**Comment by kmilos** [comment]
Just out of curiosity, how is the tag name clash between 0x0b vs 0x3f handled, as they can both exist?

**Comment by StarGeekSpaceNerd** [comment]
I would assume that it would be handled as exiftool handles any other tag with the same name. It will display both tags if the [`-a` (`-duplicates`) option](https://exiftool.org/exiftool_pod.html#a---a--duplicates---duplicates) is included, otherwise exiftool will display the contents of the last one it reads from the file.
