### ISSUE TITLE
Can't locate PAR.pm in @INC (you may need to install the PAR module) (@INC contains: .) at -e line 629

### ISSUE THREAD

**Issue by BobFrankston** [exiftool/exiftool#167]
Exiftool has been working fine for years and years, but suddenly it is complaining about 

```
Can't locate PAR.pm in @INC (you may need to install the PAR module) (@INC contains: .) at -e line 629
```

My guess is that it is necessary to install some PERL tool, but it is unclear which and where to find it. Ideally, it can be installed using a tool like WINGET or CHOCO, but the instructions should be more explicit about the remedy.

**Comment by StarGeekSpaceNerd** [comment]
Is this happening no matter what file you run exiftool on?

If this is under Windows, then it seems that cached copy may have gotten corrupted.  Hit the Windows START button or Win-R and type `%temp%` and then hit enter.  That will open up the TEMP directory.  Look for a directory that starts `par-`  and then 10 numbers/letters.  It should be the only one in the TEMP directory.  On my machine, it's called `par-626b772d4d` but it won't be the same for yours.  You can go ahead and delete it.

Next time you run exiftool, it will recreate this par directory and extract the files needed to run exiftool into it.

You might also check the drive to make sure it isn't failing, because it definiately would be unusual for something like this to happen, especially if you haven't just changed the exiftool version.

**Comment by BobFrankston** [comment]
I uninstalled and reinstalled to be safe. And I just deleted the par- directory 
```
rmdir par-426f62 /s /q
```
Command line is
```
exiftool -j .
```
but I still get
```
Can't locate PAR.pm in @INC (you may need to install the PAR module) (@INC contains: .) at -e line 629
```
After running it recreated the PAR- directory with the same name.

I even installed PERL, just in case. 

As a general suggestion -- if there are standard fixes, the message should suggest them or point to a how-to URL.

Other suggestions (I'm very experienced so you skip ahead to the geek version).

**Comment by StarGeekSpaceNerd** [comment]
To verify, you are using  Windows?

Where did you put exiftool?  If it is in `\Windows\System32`, then try moving it up a directory.  Or make sure that any antivirus software has an exception for exiftool

Another option would be to use [Oliver Betz's Alternative exiftool build](https://oliverbetz.de/pages/Artikel/ExifTool-for-Windows).  This version includes an installer and creates a PATH to exiftool.  The Chocolatey version is also a good choice as the maintainer of that keeps it up to date.

This is not a standard problem, so there's no simple solution.  Installing Perl doesn't change anything because the Windows executable contains a Perl interpreter on it's own.

**Comment by BobFrankston** [comment]
The path is
```
C:\ProgramData\chocolatey\bin\exiftool.exe
```
because  I installed it using choco

I'm wary about futzing too much. I did try moving it w32 and got
```
..\\lib\exiftool\tools\exiftool.exe
```
so not sure.

Next time I have time I can try out the alternative one. Thanks

**Comment by BobFrankston** [comment]
Solved -- OK, kludged around. I tried uninstalling, but it got bolloxed up because it was intertwined with exiftool so I just ended up renaming the exe to exex.

In then installed using winget (it was oldver -- 44 -- but I don't care)

The winget install works fine.
