### ISSUE TITLE
Question would exiftool -all= -CommonIFD0= sometiff.tiff delete all exif information from tiff file

### ISSUE THREAD

**Issue by evil-user** [exiftool/exiftool#187]
would like to know if exiftool -all= -CommonIFD0= sometiff.tiff delete all exif information from tiff file , would it compromise any image quality? I am looking to scrub unwanted metadata to improve privacy hence using above mentioned command.

**Comment by boardhead** [comment]
This should delete most standard metadata from the first image of a TIFF file.  It will not delete some metadata such as non-standard information or metadata in subsequent image of a multi-image TIFF.

Test it on your particular files, and use ExifTool to extract any remaining metadata (with "exiftool -a -u") to see if any sensitive data remains.

- Phil

**Comment by StarGeekSpaceNerd** [comment]
This is [exiftool FAQ #17](https://exiftool.org/faq.html#Q17).  You may have to check the image just in case, because there are plenty of programs out there that write incorrect EXIF data.  For example, one camera company writes `ModifyDate` to `IFD1` instead of the correct location of `IFD0`.

Additionally, using `-All=`  will removed any ICC_Profile data, which can alter the images colors.  For that, you would want to add `-TagsFromFile @ -ColorSpaceTags` at some point after the `-All=` to copy the color data back into the file.
