### ISSUE TITLE
Writing of MPG files is not yet supported

### ISSUE THREAD

**Issue by Scyth3934** [exiftool/exiftool#197]
Writing of MPG files is not yet supported

Just a reminder that this hasn't yet been implemented.

**Comment by boardhead** [comment]
As far as I know, MPG supports only ID3 metadata.  Unfortunately, the ID3 specification writers were brain dead, and supporting this metadata format must be done by trial and error because the specification is inadequate.  I don't have the time or the resources to implement this in any reliable fashion.
