### ISSUE TITLE
exiftool crashes when writing an image's makernotes to itself

### ISSUE THREAD

**Issue by pens** [exiftool/exiftool#228]
I've run into an issue where `exiftool` is crashing when trying to assign a file's makernotes to itself.

I'm trying to investigate why exiftool is dying during writes to my RAW images from `digikam`. I'm happy to provide the problematic image in question via email or DM.

## Repro

I'm running the following command:
```
exiftool -TagsFromFile @ -makernotes bad_makernotes.CR3
```
This results in the following output and an exit code of 255:
```
Warning: [minor] Invalid CanonCameraSettings data - bad_makernotes.CR3
substr outside of string at lib/Image/ExifTool.pm line 5460.
Use of uninitialized value in addition (+) at lib/Image/ExifTool/Fixup.pm line 150.
substr outside of string at lib/Image/ExifTool.pm line 5437.
```

### Setup

1. Ubuntu 23.04
2. exiftool 12.68
3. Canon CR3

## Workaround

I can, however, successfully run
```
exiftool -TagsFromFile @ -makernotes:all bad_makernotes.CR3
```
with the following output:
```
Warning: [minor] Invalid CanonCameraSettings data - bad_makernotes.CR3
    1 image files updated
```
At this point, the original command (with `-makernotes`, not `-makernotes:all`) will succeed.
`diff` shows that `-makernotes:all` doesn't appear to be dropping any metadata that `exiftool` is able to parse:
```
< [MakerNotes]    Focal Type                      : Unknown (4530)
---
> [MakerNotes]    Base ISO                        : 12800
95a96
> [MakerNotes]    Focal Type                      : Unknown (4530)
97d97
< [MakerNotes]    Base ISO                        : 12800
```
**Question:** I'm suspect that this is somehow dropping makernotes that `exiftool` is unable to parse. Is this workaround actually safe?

**Comment by boardhead** [comment]
Thanks for this report.  Could you send the sample CR3 to philharvey66 at gmail.com ?  Thanks.

- Phil

**Comment by pens** [comment]
Hi Phil, I've just sent it over. Thanks!

**Comment by boardhead** [comment]
I got the file, thanks.

The problem is related to the fact that there are 2 copies of the maker notes in the file.  This is ExifTool's fault since it is currently writing the maker notes in the ExifIFD instead of CMT3 as Canon does.  ExifTool 12.68 and earlier didn't have the ability to write the maker notes as a CMT3 block (although it would edit individual tags).  I will add this ability in 12.69 and patch the problem that causes the crash.  To remove the problem maker notes from this file, use the following command with ExifTool 12.69 (when it is available):

`exiftool -exififd:makernotes= FILE`

**Comment by pens** [comment]
Awesome, thanks so much for your help Phil!
