### ISSUE TITLE
How does reading lensid work?

### ISSUE THREAD

**Issue by Offerel** [exiftool/exiftool#264]
This is not exactly a exiftool question, basically I try to solve this issue in PHP with `$exifarray = exif_read_data($imagefile)`. 

When I use `exiftool -lensid /path/to/imagefile`, I get exactly the info what I need. But with `exif_read_data()` I couldn't find neither a string or id or anything else which is close to a reliable id or string to identify the lens.

Can someone please tell me, how exiftool can identify the correct lens? Which exif fields can I use?

**Comment by StarGeekSpaceNerd** [comment]
`LensID` isn't an actual tag in the file. It is a [Composite tag](https://exiftool.org/TagNames/Composite.html) that is created on the fly by looking at multiple different tags and checking the results against a lookup table of known lenses.  And even this isn't 100% perfect because the same data might apply to multiple different lenses.

If you look at the entry for `LensID` on the link above, you'll see that it is split into five different groups, with each one looking at different sets of data to figure what lens was used.

All of this data wasn't copy/pasted from some source.  It was built up over the past decade+ from information gathered from users and other programs, such as `LibRaw`. See the [Post your LensType / LensID discoveries here](https://exiftool.org/forum/index.php?topic=3833.0) thread on the Exiftool forums.

**Comment by Offerel** [comment]
Ok. So this means, I have no chances to find or compute such things with PHP, without deeper knowledge...

**Comment by StarGeekSpaceNerd** [comment]
Unfortunately, yes. And since some of the data will appear in the MakerNotes, I doubt you'll be able to use `exif_read_data` to access that data.  The MakerNotes format differ between companies, and often between different models from the same company. I doubt that the `exif_read_data` is updated as often as necessary to keep track of all these changes.
