### ISSUE TITLE
Writing "Orientation" may not work when specified as int value

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#265]
Instead of "Rotate 90 CW" alike.
    E.g. "-[Orientation](https://exiftool.org/TagNames/EXIF.html)=6" [2]
    “Warning: Can't convert IFD0:Orientation (not in PrintConv)
    Nothing to do.”
    .
    Test commands:
    `exiftool -v5 "-Orientation=6" -overwrite_original "in.jpg"`
    `exiftool "-*=" "-CommonIFD0=" "-Orientation=Rotate 90 CW" -overwrite_original "in.jpg"`
    [ Both seem to write more [1] than just specified tags: unsure if intended. ]

    ExifTool 12.85.

[ [1]
    Namely:
    |&#x2A;| [ExifByteOrder](https://exiftool.org/TagNames/Extra.html)
    |&#x2A;| XResolution
    |&#x2A;| YResolution
    |&#x2A;| ResolutionUnit
    |&#x2A;| YCbCrPositioning

    It appears, except "ExifByteOrder": all can be deleted. (by manual specifying) ]

[ [2]
    However specifying "-Orientation=8" would work... however for "Rotate 180".
    Bad conversion appears. ]

    ----

    Probably the writing excessive tags one should be raised as new issue?
    (unsure about the exact influence range, for various writing)

    Somewhat related: [ https://github.com/exiftool/exiftool/issues/258](https://github.com/exiftool/exiftool/issues/258)

**Comment by MasterInQuestion** [comment]
Found this...
    https://exiftool.org/exiftool_pod.html#n---printConv

    Feels unnatural for this case, regardless.

**Comment by StarGeekSpaceNerd** [comment]
From the [EXIF Tags page](https://exiftool.org/TagNames/EXIF.html)
>Mandatory tags (indicated by a colon after the Writable type) may be added automatically with default values when creating a new IFD

You can suppress the creation of mandatory EXIF tags by using the [`-api NoMandatory` option](https://exiftool.org/ExifTool.html#NoMandatory).

`ExifByteOrder` isn't a tag that actually appears in the file.  It is, as is said on the [Extra Tags page](https://exiftool.org/TagNames/Extra.html) you linked
>extra information extracted or generated by ExifTool 

In this case, it is the information on whether the EXIF data has been written in [Little-endian/Big-endian byte order](https://en.wikipedia.org/wiki/Endianness).

With regards to `Orientation`, this is [FAQ #6, I get 'Can't convert TAG (not in PrintConv)' errors when writing a tag](https://exiftool.org/faq.html#Q6). Rather than having to memorize or look up the orientation number each time, exiftool uses more human-readable text. This applies to all tags with a look-up table, not just `Orientation`.  For example, the [CanonModelID](https://exiftool.org/TagNames/Canon.html#CanonModelID) has so many entries that printing the raw number would be close to useless.

The reason `-Orientation=8` gives you "Rotate 180" is because the only place "8" appears in the PrintConv lookup table for `Orientation` is in "Rotate 180". This falls under the "unambiguous short form" that exiftool allows with the PrintConv.

**Comment by MasterInQuestion** [comment]
Is it sensible to make "-api [NoMandatory](https://exiftool.org/ExifTool.html#NoMandatory)" default?
    People mostly wouldn't wish to unawarely write what they didn't intend.

    Would such create significant problems on certain formats?

**Comment by boardhead** [comment]
Here are my thoughts on mandatory tags: https://exiftool.org/writing.html#Mandatory

ExifTool attempts to adhere to the relevant specifications when writing, which unfortunately requires writing mandatory tags in EXIF.

- Phil
