### ISSUE TITLE
`exiftool -b -ThumbnailImage` not respect Orientation tag in the image, making the thumbnail maloriented.

### ISSUE THREAD

**Issue by amalgame21** [exiftool/exiftool#266]
`exiftool -b -ThumbnailImage` not respect Orientation tag in the image, causing other bug of other program like `nsxiv`.
https://codeberg.org/nsxiv/nsxiv/issues/278#issuecomment-632879

**Comment by StarGeekSpaceNerd** [comment]
This is not a bug.  Exiftool is extracting the image exactly as it appears in the file.  If the thumbnail doesn't have an orientation, then that is because whatever program/camera created the file didn't set it.

In older versions of exiftool, if you needed the thumbnail to have an orientation, you would have to add it after extraction. But as of version 12.83, there is the new [`SetTags` helper function](https://exiftool.org/forum/index.php?msg=85548) which will copy tags from the original image to extracted thumbnails, but it may require a change to the command used.

**Comment by boardhead** [comment]
As StarGeek says, using SetTags will get what you want:

`exiftool -b -p '${thumbnailimage;SetTags("Orientation")}'`

Note that the quoting above is shell dependent.

- Phil
