### ISSUE TITLE
"-fileOrder gpsdatetime" is not correctly ordering <trkpt> by time in Inverse Geotagging output GPX file (Nextbase 422GW dashcam)

### ISSUE THREAD

**Issue by AirBiscuit** [exiftool/exiftool#281]
The output GPX file from the following command with the fileOrder flag is not correctly sorted chronologically. I have had multiple GPX file start in the middle of the path, get to the end, have a lot of dead space, and then rubberband back to the start of the video GPS position, then finally to reach the middle when viewed in gpx.studio to visualise the track.

![image](https://github.com/user-attachments/assets/a91ca66e-f9f0-4e7d-af82-a92732fce4c8)

This is the output from the following command (file extensions changed to txt to upload here): `exiftool -p gpx.fmt -fileOrder gpsdatetime -ee3 -w OutputTrace.gpx 422GW_GPX.MP4`
[422GW_GPXOutputTrace-gpx.txt](https://github.com/user-attachments/files/17267638/422GW_GPXOutputTrace-gpx.txt)
I get the same result using -ee rather than ee3.

At some point in each of the output files I make it just skips back a few minutes without explanation
![image](https://github.com/user-attachments/assets/05a6acb5-94bd-4575-b6be-52b9b5b0401f)

This is the gpx.fmt file I used: 
[gpx.txt](https://github.com/user-attachments/files/17267642/gpx.txt)

The MP4 file used for this trace is [available here](https://www.dropbox.com/scl/fi/hi9ux6vjdjj7pxna4ntg1/422GW_GPX.MP4?rlkey=mdmf43s3ec96qkvasfa2b07wb&st=4meo42kv&dl=0), but the same thing happens with 28 different video files from the same journey recorded on this dashcam. 
![image](https://github.com/user-attachments/assets/4844f4f1-2c00-4043-b5f0-ddedd9cf41b6)

**Comment by boardhead** [comment]
First of all, the -fileOrder option is used to specify the order that that input files are processed.  In your command there is one input file, so this option has no effect.

Second, the reason for the duplicate GPS track is because your file contains two GPS tracks.  You can see where both are stored using the -G1 option:

  exiftool -ee -gpsdatetime -G1 422GW_GPX.MP4

I suggest ignoring the NextBase track:

exiftool -p gpx.fmt -fileOrder gpsdatetime -ee3 --nextbase:all -w OutputTrace.gpx 422GW_GPX.MP4  

	- Phil

**Comment by AirBiscuit** [comment]
Ah, apologies for the misunderstanding. After excluding the nextbase track the GPX export is perfect, thanks for clearing that up.
