### ISSUE TITLE
Export to csv 2 rows instead of 2 cols

### ISSUE THREAD

**Issue by Coding4Sec** [exiftool/exiftool#282]
Hi.

I am in doubt that I am using exiftool correct, but using command line tools is not new to me. 

When exporting the tags of a single jpg to csv, the tags are written to a row and the values in the second row.

```
exiftool -csv fname.jpg > fname.csv
```
Shouldn't this follow the pattern: all tags in a col and values in a second col? Is there a switch to change this behaviour?

tbh I can't believe that a simple task like writing to a csv is that complicated....

My workaround so far: using `-t`

I then installed latest version of exiftool, but the output remains the same.

 I piped the stdout to a txt-file. But when importing eg in `R`, the delimiter ":" is useless, since the datetime values are separated by ":". This produces mess.

I 'm stuck with  a simple task: Writing metadata to a file just to import it into excel or process with R or Python....

PS: My first intention has been to sign up to the forum, but man what a procedure to verify I am a human being!

**Comment by StarGeekSpaceNerd** [comment]
You are using it correctly. There is no switch to change it.

What if you are getting a csv file for a directory with 10s of thousands of files in it. Your way would mean that there would be 10s of thousands of columns. Most spreadsheet programs are set up so that it's easier to scroll up/down than left/right.

Also, from the [Wikipedia entry](https://en.wikipedia.org/wiki/Comma-separated_values) on CSV files    
>Comma-separated values (CSV) is a [text file](https://en.wikipedia.org/wiki/Text_file) format that uses [commas](https://en.wikipedia.org/wiki/Comma) to separate values, and [newlines](https://en.wikipedia.org/wiki/Newline) to separate records. A CSV file stores [tabular](https://en.wikipedia.org/wiki/Table_(information)) data (numbers and text) in [plain text](https://en.wikipedia.org/wiki/Plain_text), where each line of the file typically represents one data [record](https://en.wikipedia.org/wiki/Record_(computer_science)). Each record consists of the same number of [fields](https://en.wikipedia.org/wiki/Field_(computer_science)), and these are separated by commas in the CSV file.

So the "standard", as much as there is one, is that each row is a record, not each column.

> But when importing eg in R, the delimiter ":" is useless, since the datetime values are separated by ":". This produces mess.

The EXIF standard for date/time values uses the colon. You can use the [`-d` (`-dateFormat`) option](https://exiftool.org/exiftool_pod.html#d-FMT--dateFormat) to format the date in any way you would like. See the [Common Date Format Codes](https://exiftool.org/filename.html#codes) for the list of `%` codes.

You might want to export your data in a different format. I can find several options to read JSON in [this StackOverflow](https://stackoverflow.com/questions/2061897/). See the [`-j` (`-json`) option](https://exiftool.org/exiftool_pod.html#j-JSONFILE--json). XML is also an output option (see the [`-X` (`-xmlFormat`) option](https://exiftool.org/exiftool_pod.html#X--xmlFormat)).



>My first intention has been to sign up to the forum, but man what a procedure to verify I am a human being!

Unfortunately, this is a necessity, as web forums like this are often easily overrun with spam.

**Comment by boardhead** [comment]
You could also try using [tt]-exiftool -s2[/tt] and import as a data file with delimiter ": ".

- Phil
